apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: tomcat
  name: tomcat
spec:
  selector:
    k8s-app: tomcat
  type: NodePort
  ports:
  - name: tomcat
    port: 8080
    protocol: TCP
    targetPort: 8080
